let arr = [
  `What did 20 do when it was hungry? Twenty-eight.`,
  `Why is grass so dangerous? Because it's full of blades!`,
  `Why are mountains so funny? They’re hill areas.`,
  `Why wasn’t the cactus invited to hang out with the mushrooms? He wasn’t a fungi.`,
  `Why shouldn’t you fundraise for marathons? They just take the money and run.`,
  `Why does it take pirates a long time to learn the alphabet? Because they can spend years at C!`,
  `Why can't a nose be 12 inches long? Because then it would be a foot.`,
  `Why can’t you put two half-dollars in your pocket? Because two halves make a hole, and your money will fall out!`,
  `Why does a moon rock taste better than an Earth rock? It’s a little meteor.`,
  `How much do rainbows weigh? Not much. They’re actually pretty light.`,
  `A slice of apple pie costs $2.50 in Jamaica, $3.75 in Bermuda, and $3 in the Bahamas. Those are the pie-rates of the Caribbean.`,
  `Why did the football coach yell at the vending machine? He wanted his quarter back!`,
  `What kind of job can you get at a bicycle factory? A spokesperson`,
  `What does a condiment wizard perform? Saucery`,
  `What's the difference between spring rolls and summer rolls? Their seasoning.`,
  `What’s the difference between a poorly dressed man on a unicycle and a well-dressed man on a bicycle? Attire.`,
  `What’s the difference between a $20 steak and a $55 steak? February 14th.`,
  `What's the best thing about Switzerland? The flag is a big plus.`,
  `What do you call a happy cowboy? A jolly rancher.`,
  `What word can you make shorter by adding two letters? Short.`,
  `What falls, but never needs a bandage? The rain.`,
  `Which is faster, hot or cold? Hot, because you can catch cold.`,
  `What does a pickle say when he wants to play cards? "Dill me in!"`,
  `How much money does a pirate pay for corn? A buccaneer.`,
  `Where do young trees go to learn? Elementree school.`,
  `Why do bees have sticky hair? Because they use a honeycomb.`,
  `How did the student feel when he learned about electricity? Totally shocked.`,
  `What do you call a bee that can't make up its mind? A Maybe.`,
  `Why was six afraid of seven? Because 7-8-9.`,
  `How do you organize a space party? You planet.`,
  `Why couldn't the bicycle stand up by itself? It was two tired.`,
  `Why did the student eat his homework? Because his teacher told him it was a piece of cake.`,
  `What did one hat say to the other? You wait here, I'll go on ahead.`,
  `What's a cat's favorite instrument? Purr-cussion.`,
  `Why did the crab cross the road? It didn’t—it used the sidewalk.`,
  `What’s the difference between the bird flu and the swine flu? One requires tweetment and the other an oinkment.`,
  `What is the most popular fish in the ocean? The starfish.`,
  `What’s the difference between ducks and dine-and-dashers? Ducks take care of their bills.`,
  `I found a lion in my closet the other day! When I asked what it was doing there, it said “Narnia business.”`,
  `What's the difference in an alligator and a crocodile? You’ll see one later and one in a while.`,
  `I went to the aquarium this weekend, but I didn’t stay long. There’s something fishy about that place.`,
  `Why did the snail paint a giant S on his car? So when he drove by, people could say: “Look at that S car go!”`,
  `What subject do cats like best in school? Hiss-tory.`,
  `Why can't you make a dinosaur omelet? Because they're egg-stinct.`,
  `How many goats does it take to change a lightbulb? Just one, but you have to goat them into it.`,
  `Did you hear about the new squirrel diet? It's just nuts.`,
  `When does a hippo have a tusk? After some rhino-plasty.`,
  `What did the snail who was riding on the turtle's back say? Wheeeee!`,
  `What do you call a lazy kangaroo? A pouch potato.`,
  `What does a pig put on dry skin? Oinkment.`,
  `How do you open a banana? With a mon-key.`,
  `What do you call a pony with a sore throat? A little horse.`,
  `How did the pig get to the hogspital? In a hambulance.`,
  `Why did the cow jump over the moon? The farmer had cold hands.`,
  `A termite walks into a bar and says, "So, is the bar tender here?"`,
  `How does an octopus go into battle? Well-armed.`,
  `What do you get when you mix a cocker spaniel, a poodle, and a ghost? A cocker-poodle boo.`,
  `Why don't sharks eat clowns? Because they taste funny.`,
  `A horse walks into a bar. The bartender says, "Why the long face?"`,
  `What's black and white and goes round and round? A penguin in the washing machine.`,
  `What do you call a dinosaur that crashes his car? Tyrannosaurus Wrecks.`,
  `How do you stop a bull from charging? Cancel its credit card.`,
  `Why don’t we see elephants hiding in trees? Because they’re really good at it.`,
  `What’s the difference between a hippo and a zippo? One’s pretty heavy and the other’s a little lighter.`,
  `How do you make holy water? You boil the hell out of it.`,
  `I couldn't figure out why the baseball kept getting larger. Then it hit me.`,
  `What do you call a boomerang that won’t come back? A stick.`,
  `What did the full glass say to the empty glass? You look drunk.`,
  `Justice is a dish best served cold. Otherwise, it's just water.`,
  `What do call a criminal landing an airplane? Condescending.`,
  `Why should you never throw grandpa's false teeth at a vehicle? You might denture car.`,
  `Why are Christmas trees bad at knitting? They always drop their needles.`,
  `What did the lunch box say to the refrigerator? Don't hate me because I'm a little cooler.`,
  `Did you hear about the fragile myth? It was busted.`,
  `I can always tell when someone is lying. I can tell when they're standing too.`,
  `Why did the egg hide? It was a little chicken.`,
  `What did the dirt say to the rain? If you keep this up, my name will be mud!`,
  `Why couldn't the sunflower ride its bike? It lost its petals.`,
  `What's the coolest element in the periodic table? Ber-yllium`,
  `I used to be afraid of speed bumps. I'm trying to get over it.`,
  `If your house is cold, just stand in the corner. It’s always 90 degrees there.`,
  `I don't recommend entering a wormhole. You might get stuck in the apple.`,
  `The owner of the tuxedo store kept hovering over me when i was browsing, so I asked him to leave me alone. He said, “Fine, suit ,ourself`,
  `Why did the egg have a day off? Because it was Fryday.`,
  `Have you ever heard about the kidnapping at school? It's okay, he woke up.`,
  `Why did the coffee taste like dirt? Because it was ground just a few minutes ago.`,
  `Why do quarterbacks tell obvious jokes? So they don't go over their receivers' heads.`,
  `What is the best present? Broken drums! You can't beat them.`,
  `Why do people who live in Greece hate waking up at dawn? Because Dawn is tough on Greece.`,
  `What month is the shortest of the year? May, it only has three letters.`,
  `Why do we tell actors to "break a leg?" Because every play has a cast.`,
  `What do you call it when a snowman throws a tantrum? A meltdown.`,
  `My uncle named his dogs Timex and Rolex. They're his watch dogs.`,
  `Did you hear about the guy whose left side was cut off? He's all right now.`,
  `What did the left eye say to the right eye? Between you and me, something smells.`,
  `I'm so good at sleeping I can do it with my eyes closed!`,
  `What do you call a pudgy psychic? A four-chin teller.`,
  `If April showers bring May flowers, what do May flowers bring? Pilgrims.`,
  `What do you call a hippie's wife? Mississippi.`,
  `How can you tell it’s a dogwood tree? By the bark.`,
  `What did the buffalo say when his kid went to college? Bison.`,
  `What's the stinkiest planet? Poopiter.`,
  `What did the pirate say when he turned 80? Aye matey.`,
  `Did you hear the one about the roof? Never mind, it's over your head.`,
  `What's a ninja's favorite type of shoes? Sneakers.`,
  `What's the best smelling insect? A deodor-ant.`,
  `Why was the coach yelling at the vending machine? He wanted his quarter back.`,
  `I had a joke about paper today, but it was tearable.`,
  `I made song about tortilla once, now it's more like a wrap.`,
  `Some people pick their nose, but I was born with mine.`,
  `I tried to catch fog yesterday, but I mist.`,
  `I found a book called How to Solve 50% of Your Problems, so I bought 2.`,
  `I used to be afraid of speed bumps, but I'm trying to get over it.`,
  `Corduroy pillows are in style because they're making headlines.`,
  `I decided to sell my vacuum cleaner because was just gathering dust.`,
  `I stayed up all night wondering where the sun went, and then it dawned on me.`,
  `I was going to tell you a joke about boxing but I forgot the punch line.`,
  `I'm not a fan of spring cleaning. Let's be honest, I'm not into summer, fall, or winter cleaning either.`,
  `I ate a sock yesterday. It was very time-consuming.`,
  `I wanted to buy some camo pants but couldn't find any.`,
  `I ordered a chicken and an egg from Amazon. I'll let you know.`,
  `I was going to tell a time traveling joke, but you guys didn't like it.`,
  `I used to run a dating service for chickens, but I was struggling to make hens meet.`,
  `My wife told me to stop acting like a flamingo, so I had to put my foot down.`,
  `I used to hate facial hair...but then it grew on me.`,
  `What’s the difference between Iron Man and Aluminum Man? Iron Man stops the bad guy. Aluminum Man foils their plans.`,
  `Humpty Dumpty had a great fall. He said his summer was pretty good too.`,
  `My boss said “dress for the job you want, not for the job you have.” So I went in as Batman.`,
  `What do Keanu Reeves and baby Yoda have in common? They age at the same rate.`,
  `Why did the Rolling Stones stop making music? Because they got to bottom of the hill.`,
  `Where does Batman go to the bathroom? The batroom.`,
  `Why does Humpty Dumpty love autumn? Because he had a great fall.`,
  `How do celebrities stay cool? They have many fans.`,
  `What did one snowman say to the other snowman? It smells like carrots over here!`,
  `What does a nosey pepper do? It gets jalapeño business.`,
  `What did the mama tomato say to the baby tomato? Catch up!`,
  `Why didn't the melons get married? Because they cantaloupe.`,
  `What happens when a strawberry gets run over crossing the street? Traffic jam.`,
  `What do you call a fake noodle? An impasta.`,
  `Did you hear about the pirate who became a great chef? He mastered the seven sea-sonings.`,
  `What did one plate say to the other plate? Dinner's on me.`,
  `Why do oranges wear sunscreen? So they don't peel.`,
  `What do you call a pig that does karate? A pork chop.`,
  `What's an egg's favorite vacation spot? New Yolk City.`,
  `What kind of candy do astronauts like? Mars bars.`,
  `Did you hear about the spatula's hot new flame? It met the grill of its dreams.`,
  `What did one cupcake say to the other? You ain't see muffin yet.`,
  `Two peanuts were walking down the street. One was a-salted.`,
  `What did the mayonnaise say when the refrigerator door was opened? Close the door, I'm dressing.`,
  `A cheese factory exploded in France. Da brie was everywhere.`,
  `What do you call a bear without any teeth? A gummy bear.`,
  `Did you hear the rumor about butter? Well, I'm not going to spread`,
];

// document.write(arr[random]);
let btn = document.getElementById("btn");

let joke = document.getElementById("joke");
btn.addEventListener("click", () => {
  let random = Math.floor(Math.random() * arr.length);
  joke.innerText = arr[random];
});
